### ISSUE TITLE
Justificación del proyecto

### ISSUE THREAD

**Issue by Lainezz** [aanillo/APIRESTPedidos#1]
Recuerda que en el README deben aparecer los siguientes campos:
a.
Nombre del proyecto
b.
Idea del proyecto
c.
Justificación del proyecto
d.
Descripción detallada de las tablas que intervendrán en el proyecto

La justificación del proyecto no la he visto. Esta justificación debe hablar sobre tu proyecto. Puedes imaginarte este campo preguntándote, ¿Por qué crees que se necesita una aplicación como la tuya? 

Mucho ánimo Alfonso, y gran trabajo!!

**Comment by aanillo** [comment]
Buenos días

Ya he realizado la entrega del PDF con la justificación y he editado el
README. Muchas gracias por avisar con antelación.
